version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: ticket-booking-mysql
    environment:
      MYSQL_DATABASE: ticketdb
      MYSQL_USER: ticket_user
      MYSQL_PASSWORD: ticket_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    container_name: ticket-booking-redis
    command: redis-server --requirepass redis@1234
    ports:
      - "6379:6379"

  app:
    container_name: ticket-booking-app
    build: .
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ticketdb
      DB_USER: ticket_user
      DB_PASSWORD: ticket_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis@1234